---
title: "Tidy data"
author: "Marie Rivers"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", "")) # vector or common missing values

```

## reshae so that year is a single column
```{r}
wb_indicators_long <- wb_indicators %>% 
  pivot_longer(col = '2001 [YR2001]':'2020 [YR2020]',
               names_to = "year",
               values_to = "indicator_value")

# to actually change wb_indicators, you would have to store it using wb_indicators <- wb_indicators %>% 
```
## clean up the year column
```{r}
# these steps could be combined with a pipe
# the year column is currently class "character"
# tidyr::separate()
class(wb_indicators_long$year)
wb_data_sep <- wb_indicators_long %>% 
  separate(col = year, into = c("year", "year_chr"), sep = " ") %>% # vector of new column names
  select(-year_chr, -'Country Code', -'Series Code')  # remove unneeded columns with a negative sign. Use quotes if there's a space. Or, you could type `select(-c(year_chr, 'Country Code', 'Series Code')
```
## pivot wider to get all indicators in their own column
```{r}
# use drop_na to drop missing values. Careful...this does case deletion
wb_data_tidy <- wb_data_sep %>% 
  drop_na('Series Name') %>% 
  pivot_wider(names_from = 'Series Name',
              values_from = indicator_value)
# the structure of this data is now tidy
# remane column names
# use names(wb_data_tidy) to get all current column names
names(wb_data_tidy) <- c("country", "year", "access_clean_fuels", "access_electricity", "co2_emissions", "fossil_fuel_cons", "water_resources") # replace all column names with this vector

# use the rename function to just rename 1 or more column(s). Give it `new name = old name`
wb_data_tidy <- wb_data_tidy %>% 
  rename(country_name = country,
         electricity = access_electricity)
```


```{r}
# `~` refers to a column header
# tribble in dplyr
df <- tribble(
  ~name, ~A, ~B, ~C,
  "teddy", 4, 5, 6,
  "khora", 9, 10, 11
)
df
# if A, B, and C are dog food types, convert this into tidy format
df_long <- df %>% 
  pivot_longer(col = A:C,
names_to = "dog_food",
values_to = "rankings")

df_long

df_wide <- df_long %>% 
  pivot_wider(names_from = dog_food,
              values_from = rankings)

df_wide
```

